[package]
name = "bitty-ui"
description = "View, layout and selection primitives for Bitty"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "MIT OR Apache-2.0"
repository = "https://github.com/bitty-terminal/bitty"
keywords = ["ui", "layout", "terminal", "bitty"]
categories = ["gui", "data-structures"]
publish = true

[lints]
workspace = true

[dependencies]
bitty-term-state = { version = "0.0.1", path = "../bitty-term-state" }


[dev-dependencies]
bitty-term-state = { version = "0.0.1", path = "../bitty-term-state" }
bitty-vt = { version = "0.0.1", path = "../bitty-vt" }
