[workspace]
members = [
    "crates/bitty-app",
    "crates/bitty-core",
    "crates/bitty-platform",
    "crates/bitty-pty",
    "crates/bitty-vt",
    "crates/bitty-term-state",
]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
publish = false

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
