[package]
name = "bitty-plugin-host"
description = "Draft plugin platform host for Bitty"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "MIT OR Apache-2.0"
repository = "https://github.com/bitty-terminal/bitty"
keywords = ["plugin", "bitty"]
categories = ["command-line-utilities"]
publish = false

[lints]
workspace = true

[dependencies]
bitty-term-state = { path = "../bitty-term-state" }
bitty-config = { path = "../bitty-config" }
bitty-package = { path = "../bitty-package" }
